version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wallet
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - RABBITMQ_HOST=rabbitmq  # Использование имени сервиса RabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUAL_HOST=/
      - WALLET_QUEUE_NAME=wallet_operations_queue
    depends_on:
      - db
      - rabbitmq  # Зависимость от RabbitMQ

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management  # Используется версия с интерфейсом управления
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"  # Для подключения из приложения
      - "15672:15672" # Для веб-интерфейса управления RabbitMQ
